apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnode-busybox
  labels:
    app: vnode-busybox
spec:
  selector:
    matchLabels:
      app: vnode-busybox
  template:
    metadata:
      labels:
        app: vnode-busybox
    spec:
      runtimeClassName: vnode
      containers:
        - name: vnode
          image: busybox
          command:
            - /bin/sh
          args:
            - '-c'
            - sleep 10000
          securityContext:
            privileged: true
          volumeMounts:
          - name: host-fs
            mountPath: /host
      hostNetwork: true
      hostPID: true
      hostUsers: true
      nodeSelector:
        kubernetes.io/hostname: i-03437d75b087648da.us-east-2.compute.internal
#        kubernetes.io/hostname: gke-loft-prod-worker-na-e2-node-pool-5beaac39-hv6l
      volumes:
      - name: host-fs
        hostPath:
          path: /
