apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-busybox
  labels:
    app: base-busybox
spec:
  selector:
    matchLabels:
      app: base-busybox
  template:
    metadata:
      labels:
        app: base-busybox
    spec:
      containers:
        - name: base
          image: busybox
          command:
            - /bin/sh
          args:
            - '-c'
            - sleep 10000
          securityContext:
            privileged: false
          volumeMounts:
          - name: host-fs
            mountPath: /host
      hostUsers: true
      nodeSelector:
         kubernetes.io/hostname: i-03437d75b087648da.us-east-2.compute.internal
#        kubernetes.io/hostname: gke-loft-prod-worker-na-e2-node-pool-5beaac39-hv6l
      volumes:
      - name: host-fs
        hostPath:
          path: /
